export const SUBJECT_COLORS:Record<string,string>={física:'#6366F1',fisica:'#6366F1',química:'#10B981',quimica:'#10B981',biologia:'#14B8A6',linguagens:'#F59E0B',redação:'#EC4899',redacao:'#EC4899',humanas:'#F97316',matemática:'#3B82F6',matematica:'#3B82F6',geral:'#64748B'};
export const SUBJECT_LOGOS:Record<string,string>={física:'/subject-logos/fisica.svg',fisica:'/subject-logos/fisica.svg',redação:'/subject-logos/redacao.svg',redacao:'/subject-logos/redacao.svg',linguagens:'/subject-logos/linguagens.svg',biologia:'/subject-logos/biologia.svg',química:'/subject-logos/quimica.svg',quimica:'/subject-logos/quimica.svg',humanas:'/subject-logos/humanas.svg',matemática:'/subject-logos/matematica.svg',matematica:'/subject-logos/matematica.svg',geral:'/subject-logos/geral.svg'};
export const SUBJECT_TEACHERS:Record<string,string[]>={};
export function normalizeSubjectText(value?:string|null):string{return(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
export function subjectColor(name?:string|null,color?:string|null):string{if(color&&/^#[0-9a-f]{6}$/i.test(color))return color;return SUBJECT_COLORS[(name||'').trim().toLowerCase()]||'#64748B'}
export function subjectCode(name?:string|null,code?:string|null):string{if(code?.trim())return code.trim().toUpperCase();return(name||'MAT').replace(/[^A-Za-zÀ-ÿ0-9]/g,'').slice(0,4).toUpperCase()||'MAT'}
export function subjectLogo(name?:string|null,logoPath?:string|null):string|null{if(logoPath?.trim())return logoPath;return SUBJECT_LOGOS[(name||'').trim().toLowerCase()]||SUBJECT_LOGOS.geral}
export function subjectTeachers(name?:string|null,teacherNames?:string[]|null):string[]{if(teacherNames?.length)return teacherNames;return SUBJECT_TEACHERS[(name||'').trim().toLowerCase()]||[]}
export function inferSubjectsFromClassName(className:string):string[]{const normalized=normalizeSubjectText(className);const found:string[]=[];const add=(subject:string)=>{if(!found.includes(subject))found.push(subject)};if(/\bredacao\b/.test(normalized))add('Redação');if(/\blinguagens?\b|\bportugues\b|\bliteratura\b/.test(normalized))add('Linguagens');if(/\bbiologia\b|\bbio\b|\bparasitologia\b/.test(normalized))add('Biologia');if(/\bquimica\b|\bgases\b|\btermodinamica\b/.test(normalized))add('Química');if(/\bfisica\b|\beletrostatica\b|\bkirchhoff\b|\boptica\b|\bondulatoria\b/.test(normalized))add('Física');if(/\bhumanas\b|\bhistoria\b|\bgeografia\b|\bfilosofia\b|\bsociologia\b/.test(normalized))add('Humanas');if(/\bmatematica\b/.test(normalized))add('Matemática');return found.length?found:['Geral']}
