import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Alert, Avatar, Badge, Card, EmptyState, PageHeader, ProgressBar, Sparkline, StatCard, StatusBadge } from '@/components/ui';
import { Icon } from '@/components/icon';
import { StudentAccessManager } from '@/components/student-access-manager';
import { getStudentAdminDetail } from '@/server/data/admin';
import { formatDate, formatDuration } from '@/lib/format';
import { requireManagementRoles } from '@/server/data/context';

export default async function StudentDetailsPage({ params }: { params: Promise<{ studentId: string }> }) {
  await requireManagementRoles(['admin', 'coordinator']);
  const { studentId } = await params;
  const data = await getStudentAdminDetail(studentId);
  if (!data) notFound();
  const { profile, stats } = data;
  const scores = data.attempts.filter((item) => item.status === 'submitted').slice(0, 8).reverse().map((item) => Number(item.score_normalized || 0));
  return <>{data.registryOnly ? <div className="mb-5"><Alert tone="warning">Este aluno foi importado, mas ainda não concluiu o primeiro acesso. Os vínculos abaixo já estão preparados e podem ser ajustados manualmente antes do cadastro.</Alert></div> : null}<PageHeader backHref="/admin/alunos" eyebrow="Perfil acadêmico" title={profile.full_name} description="Dados, vínculos e desempenho consultados diretamente da base oficial." actions={<a href="/api/admin/exports/students" className="app-button-secondary"><Icon name="download" className="h-4 w-4" /> Exportar base</a>} />
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><aside className="space-y-6"><Card><div className="flex flex-col items-center text-center"><Avatar name={profile.full_name} size="lg" className="h-24 w-24 text-2xl" /><h2 className="mt-4 text-lg font-bold text-white">{profile.full_name}</h2><p className="mt-1 text-sm text-[#777]">{data.registryOnly ? 'Aguardando primeiro acesso' : `@${profile.nickname}`}</p><div className="mt-3"><StatusBadge status={profile.status} /></div></div><div className="mt-6 space-y-4 border-t border-[#292929] pt-5 text-sm"><Info icon="mail" label="E-mail" value={profile.email} /><Info icon="id-card" label="CPF protegido" value={`***.***.***-${String(profile.cpf_last4).slice(-2)}`} /><Info icon="graduation" label="Turmas" value={[...new Set(data.enrollments.map((item) => item.className))].join(', ') || 'Sem vínculo'} /><Info icon="history" label="Cadastro" value={formatDate(profile.created_at, true)} /></div></Card><Card title="Vínculos e controle de acesso" description="Bloqueie somente a turma inadimplente sem remover os demais acessos do aluno."><StudentAccessManager studentId={profile.id} enrollments={data.enrollments} classes={data.availableClasses} subjects={data.availableSubjects} />{data.pendingContracts.length ? <div className="mt-4 border-t border-[#2b2b2b] pt-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-amber-300">Contratos pendentes</p><div className="mt-2 space-y-2">{data.pendingContracts.map((contract) => <div key={contract.id} className="border border-amber-500/25 bg-amber-500/5 p-3 text-xs text-amber-200">{contract.contract_name}</div>)}</div></div> : null}</Card></aside>
      <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Média geral" value={stats.average.toFixed(1)} icon="target" tone="primary" /><StatCard label="Tentativas" value={stats.attempts} icon="clipboard" tone="neutral" /><StatCard label="Melhor nota" value={stats.best.toFixed(1)} icon="trophy" tone="success" /><StatCard label="Acertos totais" value={stats.totalCorrect} icon="check-circle" tone="purple" /></div>
        <Card title="Evolução do aluno" description="Notas das últimas avaliações concluídas">{scores.length > 1 ? <div className="h-40 text-white"><Sparkline values={scores} className="h-full" /></div> : <EmptyState icon="chart" title="Ainda sem histórico suficiente" description="São necessárias ao menos duas tentativas concluídas." />}</Card>
        <Card title="Desempenho por matéria"><div className="grid gap-4 md:grid-cols-2">{data.performance.map((item) => <div key={item.id} className="rounded-md border border-[#333] bg-[#171717] p-4"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }} /><p className="font-bold text-white">{item.name}</p></div><span className="text-sm font-black">{item.average.toFixed(1)}</span></div><ProgressBar value={item.average} color={item.color} /><p className="mt-2 text-xs text-[#777]">{item.attempts} tentativa(s) · melhor {item.best.toFixed(1)}</p></div>)}{!data.performance.length ? <EmptyState icon="layers" title="Sem desempenho por matéria" description="Os resultados aparecerão após a primeira tentativa concluída." /> : null}</div></Card>
        <Card title="Tentativas recentes" padding={false} action={<Link href="/admin/relatorios" className="text-sm font-bold text-white">Ver relatórios</Link>}><div className="overflow-x-auto"><table className="app-table min-w-[760px]"><thead><tr><th>Simulado</th><th>Status</th><th>Data</th><th>Nota</th><th>Tempo</th></tr></thead><tbody>{data.attempts.slice(0, 20).map((attempt) => <tr key={attempt.id}><td><p className="font-bold text-white">{attempt.quizTitle}</p><Badge className="mt-1"><i className="h-2 w-2 rounded-full" style={{ background: attempt.subjectColor }} />{attempt.subject}</Badge></td><td><StatusBadge status={attempt.status} /></td><td>{formatDate(attempt.submitted_at || attempt.started_at, true)}</td><td className="font-black">{attempt.score_normalized == null ? '—' : Number(attempt.score_normalized).toFixed(1)}</td><td>{formatDuration(Number(attempt.duration_seconds || 0))}</td></tr>)}{!data.attempts.length ? <tr><td colSpan={5}><EmptyState icon="history" title="Nenhuma tentativa" description="O aluno ainda não iniciou simulados." /></td></tr> : null}</tbody></table></div></Card>
      </div></div>
  </>;
}

function Info({ icon, label, value }: { icon: 'mail' | 'id-card' | 'graduation' | 'history'; label: string; value: string }) { return <div className="flex gap-3"><Icon name={icon} className="mt-0.5 h-5 w-5 text-[#777]" /><div className="min-w-0"><p className="text-xs text-[#777]">{label}</p><p className="mt-1 break-words font-semibold text-[#ddd]">{value}</p></div></div>; }
