import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Avatar, Badge, Card, EmptyState, PageHeader, ProgressBar, StatCard, StatusBadge } from '@/components/ui';
import { Icon } from '@/components/icon';
import { getClassAdminDetail } from '@/server/data/admin';
import { formatDate } from '@/lib/format';
import { requireManagementRoles } from '@/server/data/context';

export default async function ClassDetailsPage({ params }: { params: Promise<{ classId: string }> }) {
  await requireManagementRoles(['admin', 'coordinator']);
  const { classId } = await params;
  const data = await getClassAdminDetail(classId);
  if (!data) notFound();
  const item = data.class;
  return <><PageHeader backHref="/admin/turmas" eyebrow={item.code || 'TURMA'} title={item.name} description={item.description || 'Visão consolidada da turma com dados reais.'} actions={<Link href="/admin/turmas" className="app-button-secondary"><Icon name="edit" className="h-4 w-4" /> Gerenciar turma</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Alunos" value={data.stats.students} icon="users" tone="primary" /><StatCard label="Matérias" value={data.stats.subjects} icon="layers" tone="purple" /><StatCard label="Média" value={data.stats.average.toFixed(1)} icon="chart" tone="success" /><StatCard label="Participação" value={`${data.stats.participation}%`} icon="target" tone="warning" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><Card title="Matérias" description="Escopo acadêmico real desta turma"><div className="space-y-3">{data.subjects.map((subject) => <div key={subject.id} className="flex items-center gap-3 rounded-md border border-[#333] bg-[#171717] p-3"><span className="h-9 w-1.5 shrink-0 rounded-full" style={{ backgroundColor: subject.color }} /><div className="min-w-0 flex-1"><p className="font-bold text-white">{subject.name}</p><p className="mt-1 text-xs text-[#777]">{subject.students} aluno(s) vinculado(s)</p></div></div>)}{!data.subjects.length ? <EmptyState icon="layers" title="Sem matérias" description="Adicione vínculos de alunos a matérias nesta turma." /> : null}</div></Card><Card title="Desempenho dos simulados"><div className="space-y-5">{data.quizzes.map((quiz) => <ProgressBar key={quiz.id} value={quiz.average} label={`${quiz.title} — ${quiz.average.toFixed(1)}`} color={quiz.subjectColor} />)}{!data.quizzes.length ? <EmptyState icon="clipboard" title="Sem simulados vinculados" description="Atribua um simulado a esta turma para acompanhar o desempenho." /> : null}</div></Card></div>
    <Card className="mt-6" title="Alunos da turma" padding={false} action={<Link href="/admin/alunos" className="text-sm font-bold text-white">Ver todos</Link>}><div className="overflow-x-auto"><table className="app-table min-w-[800px]"><thead><tr><th>Aluno</th><th>Apelido</th><th>Matérias</th><th>Status</th><th></th></tr></thead><tbody>{data.students.map((student) => <tr key={student.id}><td><div className="flex items-center gap-3"><Avatar name={student.full_name} size="sm" /><div><p className="font-bold text-white">{student.full_name}</p><p className="mt-1 text-xs text-[#777]">{student.email}</p></div></div></td><td>@{student.nickname}</td><td>{student.subjects}</td><td><StatusBadge status={student.status} /></td><td className="text-right"><Link href={`/admin/alunos/${student.id}`} className="app-button-secondary px-3 py-2"><Icon name="eye" className="h-4 w-4" /></Link></td></tr>)}{!data.students.length ? <tr><td colSpan={5}><EmptyState icon="users" title="Nenhum aluno vinculado" description="A turma ainda não possui matrículas ativas." /></td></tr> : null}</tbody></table></div></Card>
    <Card className="mt-6" title="Simulados vinculados" padding={false}><div className="overflow-x-auto"><table className="app-table min-w-[760px]"><thead><tr><th>Simulado</th><th>Matéria</th><th>Status</th><th>Tentativas</th><th>Média</th><th>Prazo</th></tr></thead><tbody>{data.quizzes.map((quiz) => <tr key={quiz.id}><td><Link href={`/admin/simulados/${quiz.id}`} className="font-bold text-white hover:underline">{quiz.title}</Link></td><td><Badge><i className="h-2 w-2 rounded-full" style={{ background: quiz.subjectColor }} />{quiz.subject}</Badge></td><td><StatusBadge status={quiz.status} /></td><td>{quiz.attempts}</td><td>{quiz.average.toFixed(1)}</td><td>{quiz.assignment.due_at ? formatDate(quiz.assignment.due_at, true) : 'Sem prazo'}</td></tr>)}{!data.quizzes.length ? <tr><td colSpan={6}><EmptyState icon="clipboard" title="Nenhum simulado" description="Atribua um simulado a esta turma." /></td></tr> : null}</tbody></table></div></Card>
  </>;
}
