'use client';
import { useState } from 'react';
import { Alert, EmptyState } from '@/components/ui';
import { Icon } from '@/components/icon';
type Item = { id: string; name: string; email: string; nickname: string; cpfLast4: string; requestedAt: string };
export function PasswordResetRequests({ initialRequests }: { initialRequests: Item[] }) {
  const [items, setItems] = useState(initialRequests); const [message, setMessage] = useState(''); const [temporary, setTemporary] = useState<{ name: string; password: string; warning?: string } | null>(null); const [busy, setBusy] = useState('');
  async function action(item: Item, type: 'approve' | 'reject') { if (type === 'reject' && !confirm(`Rejeitar a solicitação de ${item.name}?`)) return; setBusy(item.id); setMessage(''); const response = await fetch(`/api/admin/password-reset-requests/${item.id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: type }) }); const payload = await response.json().catch(() => null); setBusy(''); if (!response.ok) return setMessage(payload?.error?.message || 'Não foi possível analisar.'); setItems((current) => current.filter((row) => row.id !== item.id)); if (payload.data?.temporaryPassword) setTemporary({ name: item.name, password: payload.data.temporaryPassword, warning: payload.data.warning }); }
  return <div className="space-y-4">{message ? <Alert tone="danger">{message}</Alert> : null}{temporary ? <Alert tone="success" title="Senha temporária gerada"><p>Aluno: <b>{temporary.name}</b></p><p className="mt-2">Senha temporária: <code className="rounded bg-black/30 px-2 py-1 text-base font-black">{temporary.password}</code></p>{temporary.warning ? <p className="mt-2 rounded border border-amber-500/30 bg-amber-500/10 p-2 text-xs text-amber-100">{temporary.warning}</p> : null}<p className="mt-2 text-xs">Copie e entregue ao aluno agora. Esta senha não ficará visível novamente.</p><button className="app-button-secondary mt-3" onClick={() => navigator.clipboard.writeText(temporary.password)}>Copiar senha</button></Alert> : null}<div className="app-table-wrap overflow-x-auto"><table className="app-table min-w-[800px]"><thead><tr><th>Aluno</th><th>CPF</th><th>Solicitado em</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><b className="text-slate-900">{item.name}</b><p className="text-xs text-slate-500">{item.email} · @{item.nickname}</p></td><td>***.***.***-{item.cpfLast4.slice(-2)}</td><td>{new Date(item.requestedAt).toLocaleString('pt-BR')}</td><td><div className="flex gap-2"><button className="app-button-primary" disabled={busy === item.id} onClick={() => action(item, 'approve')}><Icon name={busy === item.id ? 'refresh' : 'check'} className={`h-4 w-4 ${busy === item.id ? 'animate-spin' : ''}`} /> Aprovar e gerar senha</button><button className="app-button-danger" disabled={busy === item.id} onClick={() => action(item, 'reject')}><Icon name="x" className="h-4 w-4" /></button></div></td></tr>)}{!items.length ? <tr><td colSpan={4}><EmptyState icon="check-circle" title="Nenhuma troca de senha pendente" description="Todas as solicitações foram analisadas." /></td></tr> : null}</tbody></table></div></div>;
}
