'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Alert, Card } from '@/components/ui';
import { Icon } from '@/components/icon';
import type { ClassSummary, QuizSummary, SubjectSummary } from '@/lib/domain-types';
import { cn } from '@/lib/cn';

type Props = { quiz: QuizSummary; classes: ClassSummary[]; subjects: SubjectSummary[] };
export function QuizSettingsEditor({ quiz, classes, subjects }: Props) {
  const router = useRouter();
  const [title, setTitle] = useState(quiz.title); const [description, setDescription] = useState(quiz.description || '');
  const [durationMinutes, setDurationMinutes] = useState(quiz.durationMinutes); const [plannedQuestionCount, setPlannedQuestionCount] = useState(quiz.plannedQuestionCount);
  const [subjectIds, setSubjectIds] = useState<string[]>(quiz.subjectIds); const [classIds, setClassIds] = useState<string[]>(quiz.classIds);
  const [releaseAt, setReleaseAt] = useState(toLocal(quiz.releaseAt)); const [dueAt, setDueAt] = useState(toLocal(quiz.dueAt));
  const [maxAttempts, setMaxAttempts] = useState(quiz.maxAttempts); const [showExplanation, setShowExplanation] = useState(quiz.showExplanation); const [showRanking, setShowRanking] = useState(quiz.showRanking); const [allowReview, setAllowReview] = useState(quiz.allowReview); const [shuffleQuestions, setShuffleQuestions] = useState(quiz.shuffleQuestions); const [shuffleOptions, setShuffleOptions] = useState(quiz.shuffleOptions);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ tone: 'success' | 'danger' | 'warning'; text: string } | null>(null);
  const toggle = (id: string, values: string[], setter: (value: string[]) => void) => setter(values.includes(id) ? values.filter((item) => item !== id) : [...values, id]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!subjectIds.length) return setMessage({ tone: 'warning', text: 'Selecione ao menos uma matéria.' }); if (releaseAt && dueAt && new Date(dueAt) <= new Date(releaseAt)) return setMessage({ tone: 'warning', text: 'O prazo final deve ser posterior à liberação.' }); setBusy(true); setMessage(null); try { const response = await fetch(`/api/quizzes/${quiz.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title, description: description || null, durationMinutes, plannedQuestionCount, subjectIds, classIds, releaseAt: releaseAt ? new Date(releaseAt).toISOString() : null, dueAt: dueAt ? new Date(dueAt).toISOString() : null, settings: { maxAttempts, showExplanation, showRanking, allowReview, shuffleQuestions, shuffleOptions } }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.error?.message || 'Não foi possível salvar o simulado.'); setMessage({ tone: 'success', text: 'Configurações e público atualizados.' }); router.refresh(); } catch (error) { setMessage({ tone: 'danger', text: error instanceof Error ? error.message : 'Falha ao salvar.' }); } finally { setBusy(false); } }
  async function remove() { if (!confirm(quiz.attempts ? `Excluir definitivamente este simulado e suas ${quiz.attempts} tentativa(s)?` : 'Excluir definitivamente este simulado?')) return; setBusy(true); const response = await fetch(`/api/quizzes/${quiz.id}`, { method: 'DELETE' }); const payload = await response.json().catch(() => null); if (!response.ok) { setMessage({ tone: 'danger', text: payload?.error?.message || 'Não foi possível excluir.' }); setBusy(false); return; } router.push('/admin/simulados'); router.refresh(); }
  return <Card title="Editar simulado" description="Altere disponibilidade, matérias, turmas e comportamento da avaliação."><form onSubmit={save} className="space-y-5">{message ? <Alert tone={message.tone}>{message.text}</Alert> : null}<div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="app-label">Título</label><input className="app-input" required minLength={3} value={title} onChange={(e) => setTitle(e.target.value)} /></div><div className="sm:col-span-2"><label className="app-label">Descrição</label><textarea className="app-input min-h-24" value={description} onChange={(e) => setDescription(e.target.value)} /></div><NumberField label="Questões planejadas" value={plannedQuestionCount} max={300} set={setPlannedQuestionCount} /><NumberField label="Duração em minutos" value={durationMinutes} max={600} set={setDurationMinutes} /><NumberField label="Tentativas por aluno" value={maxAttempts} max={10} set={setMaxAttempts} /><div><label className="app-label">Disponível a partir de</label><input className="app-input" type="datetime-local" value={releaseAt} onChange={(e) => setReleaseAt(e.target.value)} /></div><div><label className="app-label">Disponível até</label><input className="app-input" type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></div></div><Scope title="Matérias" items={subjects.filter((i) => i.status === 'active')} selected={subjectIds} toggle={(id) => toggle(id, subjectIds, setSubjectIds)} /><Scope title="Turmas" items={classes.filter((i) => i.status === 'active')} selected={classIds} toggle={(id) => toggle(id, classIds, setClassIds)} /><div className="grid gap-3 sm:grid-cols-2">{[["Mostrar explicação após entrega", showExplanation, setShowExplanation], ["Exibir posição no ranking", showRanking, setShowRanking], ["Permitir revisão antes de finalizar", allowReview, setAllowReview], ["Embaralhar questões", shuffleQuestions, setShuffleQuestions], ["Embaralhar alternativas", shuffleOptions, setShuffleOptions]].map(([label, checked, setter]) => <label key={String(label)} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white p-4"><input type="checkbox" checked={Boolean(checked)} onChange={(e) => (setter as (v: boolean) => void)(e.target.checked)} className="accent-orange-500" /><span className="text-sm font-semibold text-slate-700">{String(label)}</span></label>)}</div><div className="flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:justify-between">{quiz.canDelete ? <button type="button" className="app-button-danger" onClick={remove} disabled={busy}><Icon name="trash" className="h-4 w-4" /> Excluir definitivamente</button> : <span />}<button className="app-button-primary" disabled={busy}><Icon name={busy ? 'refresh' : 'save'} className={`h-4 w-4 ${busy ? 'animate-spin' : ''}`} /> Salvar alterações</button></div></form></Card>;
}
function Scope({ title, items, selected, toggle }: { title: string; items: Array<{ id: string; name: string }>; selected: string[]; toggle: (id: string) => void }) { return <div><label className="app-label">{title}</label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <label key={item.id} className={cn('flex cursor-pointer items-center gap-3 rounded-lg border p-3', selected.includes(item.id) ? 'border-orange-500 bg-orange-50' : 'border-slate-200 bg-white')}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} className="accent-orange-500" /><span className="text-sm font-semibold text-slate-900">{item.name}</span></label>)}</div></div>; }
function NumberField({ label, value, max, set }: { label: string; value: number; max: number; set: (value: number) => void }) { return <div><label className="app-label">{label}</label><input className="app-input" type="number" min={1} max={max} value={value} onChange={(e) => set(Number(e.target.value))} /></div>; }
function toLocal(value: string | null) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
