import Link from 'next/link';
import { Avatar, Badge, Card, EmptyState, PageHeader, StatCard } from '@/components/ui';
import { getStudentQuizzes, getStudentRanking } from '@/server/data/student';
import { formatDuration, formatScore } from '@/lib/format';
import { cn } from '@/lib/cn';
import { Icon } from '@/components/icon';

type SearchParams = { quizId?: string; subjectId?: string; classId?: string };
export default async function RankingPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const params = await searchParams;
  const filters = { quizId: clean(params.quizId), subjectId: clean(params.subjectId), classId: clean(params.classId) };
  const [rows, quizzes] = await Promise.all([getStudentRanking(filters), getStudentQuizzes()]);
  const subjectOptions = [...new Map(quizzes.flatMap((quiz) => quiz.subjectIds.map((id, index) => [id, quiz.subjectNames[index] || 'Matéria'] as const))).entries()];
  const classOptions = [...new Map(quizzes.flatMap((quiz) => quiz.classIds.map((id, index) => [id, quiz.classNames[index] || 'Turma'] as const))).entries()];
  const current = rows.find((item: any) => item.isCurrent); const scores = rows.map((item: any) => Number(item.score_normalized || 0)); const average = scores.length ? scores.reduce((sum, value) => sum + value, 0) / scores.length : 0; const topThree = rows.slice(0, 3); const podiumOrder = [topThree[1], topThree[0], topThree[2]].filter(Boolean); const percentile = current && rows.length ? Math.max(0, Math.round(((rows.length - Number(current.position) + 1) / rows.length) * 100)) : 0;
  return <>
    <PageHeader eyebrow="Competição saudável" title="Ranking" description="Ordem oficial: maior número de acertos, menor tempo total, maior pontuação e entrega mais antiga." />
    <form method="get" className="app-card mb-6 grid gap-4 p-5 md:grid-cols-4"><Filter label="Simulado" name="quizId" value={filters.quizId || ''} options={quizzes.map((item) => [item.id, item.title])} /><Filter label="Matéria" name="subjectId" value={filters.subjectId || ''} options={subjectOptions} /><Filter label="Turma" name="classId" value={filters.classId || ''} options={classOptions} /><div className="flex items-end gap-2"><button className="app-button-primary flex-1"><Icon name="filter" className="h-4 w-4" /> Aplicar</button><Link href="/ranking" className="app-button-secondary px-3" aria-label="Limpar filtros"><Icon name="refresh" className="h-4 w-4" /></Link></div></form>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Sua posição" value={current ? `${current.position}º` : '—'} icon="trophy" tone="warning" helper={current ? `entre ${rows.length} participantes` : 'sem classificação'} /><StatCard label="Seus acertos" value={current ? current.correct_count : '—'} icon="check-circle" tone="success" helper="primeiro critério" /><StatCard label="Sua pontuação" value={formatScore(current?.score_normalized)} icon="target" tone="primary" /><StatCard label="Percentil" value={current ? `${percentile}%` : '—'} icon="chart" tone="neutral" helper={`média ${formatScore(average)}`} /></div>
    {podiumOrder.length ? <Card className="mt-6" title="Pódio" description="Melhores resultados no recorte selecionado"><div className="grid items-end gap-4 md:grid-cols-3">{podiumOrder.map((item: any) => { const position = Number(item.position); return <div key={item.id} className={cn('flex flex-col items-center justify-end rounded-md border border-[#303030] bg-[#171717] p-5 text-center', position === 1 ? 'min-h-[245px]' : position === 2 ? 'min-h-[215px]' : 'min-h-[195px]')}><div className={cn('mb-3 flex h-8 w-8 items-center justify-center rounded-full font-black', position === 1 ? 'bg-white text-black' : 'bg-[#333] text-white')}>{position}</div><Avatar name={item.nickname || 'Aluno'} size="lg" /><p className="mt-3 font-semibold text-white">{item.nickname || 'Aluno'}</p><p className="mt-1 text-2xl font-semibold text-white">{item.correct_count} acertos</p><p className="mt-1 text-xs text-[#777]">{formatDuration(item.duration_seconds)} · {formatScore(item.score_normalized)} pts</p>{position === 1 ? <Badge tone="warning" className="mt-3">Líder</Badge> : null}</div>; })}</div></Card> : null}
    <Card className="mt-6" title="Classificação completa" description="Acertos ↓ · tempo ↑ · pontuação ↓ · data de entrega ↑" padding={false}><div className="overflow-x-auto"><table className="app-table min-w-[850px]"><thead><tr><th>Posição</th><th>Aluno</th><th>Acertos</th><th>Erros</th><th>Tempo</th><th>Pontuação</th><th>Recorte</th></tr></thead><tbody>{rows.map((item: any) => <tr key={item.id} className={item.isCurrent ? 'bg-white/[0.04]' : ''}><td><span className={cn('inline-flex h-8 min-w-8 items-center justify-center rounded-lg px-2 font-black', Number(item.position) <= 3 ? 'bg-white text-black' : 'bg-[#292929] text-[#bbb]')}>{item.position}</span></td><td><div className="flex items-center gap-3"><Avatar name={item.nickname || 'Aluno'} size="sm" /><div><p className="font-semibold text-white">{item.nickname || 'Aluno'}</p>{item.isCurrent ? <p className="text-xs font-semibold text-emerald-300">Você</p> : null}</div></div></td><td className="font-bold text-emerald-300">{item.correct_count}</td><td>{item.wrong_count}</td><td>{formatDuration(item.duration_seconds)}</td><td>{formatScore(item.score_normalized)}</td><td><Badge>{item.quiz_title || 'Geral'}</Badge></td></tr>)}{!rows.length ? <tr><td colSpan={7}><EmptyState icon="trophy" title="Sem resultados neste recorte" description="Escolha outro filtro ou aguarde tentativas concluídas." /></td></tr> : null}</tbody></table></div></Card>
  </>;
}
function Filter({ label, name, value, options }: { label: string; name: string; value: string; options: Array<readonly [string, string]> }) { return <div><label className="app-label">{label}</label><select className="app-input" name={name} defaultValue={value}><option value="">Todos</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></div>; }
function clean(value?: string) { return value && value !== 'all' ? value : undefined; }
