import Link from 'next/link';
import { Badge, Card, EmptyState, PageHeader, ProgressBar, Sparkline, StatCard, StatusBadge } from '@/components/ui';
import { Icon } from '@/components/icon';
import { getStudentDashboardData } from '@/server/data/student';
import { formatDate, formatDuration } from '@/lib/format';

export default async function DashboardPage() {
  const data = await getStudentDashboardData();
  const recentScores = data.attempts.filter((item: any) => item.status === 'submitted').slice(0, 8).reverse().map((item: any) => Number(item.score_normalized || 0));
  return <><PageHeader eyebrow="Área do aluno" title={`Olá, ${data.profile.full_name.split(' ')[0]}`} description="Acompanhe simulados, resultados e evolução na Nexo Avalia." actions={<Link href="/simulados" className="app-button-primary"><Icon name="play" className="h-4 w-4" /> Ver simulados</Link>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Disponíveis" value={data.stats.available} icon="clipboard" tone="primary" /><StatCard label="Concluídos" value={data.stats.completed} icon="check-circle" tone="success" /><StatCard label="Média" value={data.stats.average.toFixed(1)} icon="target" tone="purple" /><StatCard label="Melhor nota" value={data.stats.best.toFixed(1)} icon="trophy" tone="warning" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.8fr]"><Card title="Próximos simulados" description="Avaliações liberadas para suas turmas" action={<Link href="/simulados" className="text-sm font-bold text-white">Ver todos</Link>}><div className="space-y-3">{data.quizzes.slice(0, 5).map((quiz) => <Link key={quiz.id} href={`/simulados/${quiz.id}`} className="block rounded-md border border-[#333] bg-[#171717] p-4 transition hover:border-[#666]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: quiz.subjectColor }} /><p className="font-bold text-white">{quiz.title}</p></div><p className="mt-2 text-xs text-[#777]">{quiz.className} · {quiz.questionCount} questões · {quiz.durationMinutes} min</p></div><StatusBadge status={quiz.attempts ? 'submitted' : 'published'} /></div>{quiz.dueAt ? <p className="mt-3 text-xs text-[#999]">Prazo: {formatDate(quiz.dueAt, true)}</p> : null}</Link>)}{!data.quizzes.length ? <EmptyState icon="clipboard" title="Nenhum simulado disponível" description="As próximas avaliações aparecerão aqui quando forem publicadas." /> : null}</div></Card><Card title="Evolução recente" description="Notas das últimas tentativas">{recentScores.length > 1 ? <><div className="h-44 text-white"><Sparkline values={recentScores} className="h-full" /></div><ProgressBar value={data.stats.average} label={`Média ${data.stats.average.toFixed(1)}`} /></> : <EmptyState icon="chart" title="Comece seu histórico" description="Conclua ao menos dois simulados para visualizar a evolução." />}</Card></div>
    <Card className="mt-6" title="Atividade recente" padding={false}><div className="overflow-x-auto"><table className="app-table min-w-[760px]"><thead><tr><th>Simulado</th><th>Matéria</th><th>Status</th><th>Nota</th><th>Tempo</th><th>Data</th></tr></thead><tbody>{data.attempts.slice(0, 8).map((attempt: any) => <tr key={attempt.id}><td><Link href={attempt.status === 'submitted' ? `/resultados/${attempt.id}` : `/simulados/${attempt.quiz_id}/realizar?attemptId=${attempt.id}`} className="font-bold text-white hover:underline">{attempt.quizTitle}</Link></td><td><Badge><i className="h-2 w-2 rounded-full" style={{ background: attempt.subjectColor }} />{attempt.subject}</Badge></td><td><StatusBadge status={attempt.status} /></td><td>{attempt.score_normalized == null ? '—' : Number(attempt.score_normalized).toFixed(1)}</td><td>{formatDuration(Number(attempt.duration_seconds || 0))}</td><td>{formatDate(attempt.submitted_at || attempt.started_at, true)}</td></tr>)}{!data.attempts.length ? <tr><td colSpan={6}><EmptyState icon="history" title="Sem atividade" description="Suas tentativas aparecerão aqui." /></td></tr> : null}</tbody></table></div></Card>
  </>;
}
